In [9]:
# Custom style
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [10]:
import os
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import random

In [11]:
# Save this to make sure files are backed up
# git config --global credential.helper store
# os.system("git add . && git commit -m 'generic work progress' && git push")

In [12]:
num_customerz = 200
time_periodz = 1000
num_repz = 5

In [13]:
def generate_customer_table(num_customers, time_periods, seed=None):
    if seed is not None:
        np.random.seed(seed)

    df_customers = pd.DataFrame([i for i in range(1,num_customers+1)], columns=['customer_id'])
    df_customers['required_call_time'] = [np.random.choice([1,2,3,4,5]) for i in range(num_customers)]
    df_customers['time_in']=[np.random.choice(range(1,time_periods)) for i in range(num_customers)]
    df_customers['time_out']=[0 for i in range(num_customers)]
    df_customers['time_assigned'] = [0 for i in range(num_customers)]
    df_customers['assigned_rep'] = ['none' for i in range(num_customers)]

    df_customers=df_customers.sort_values(by='time_in')
    df_customers['customer_id'] = [i for i in range(1,num_customers+1)]
    
    return df_customers

def generate_qs(time_periods):

    df_q = pd.DataFrame([0 for x in range(time_periods)], columns=['customer_q_list'])
    df_q['customer_q_list'] = [[] for x in range(time_periods)]
    df_q['update_event'] = [0 for x in range(time_periods)]

    return df_q

def generate_reps(num_reps, time_periods):
    reps_list = ['rep' + str(i) + '_busy' for i in range(1,num_reps+1)]
    df_reps = pd.DataFrame(columns=reps_list, index=range(time_periods))
    for rep in reps_list:
        df_reps[rep] = 0

    return df_reps

In [14]:
def run_day(df_customers, df_q, df_reps, iteration, time_periods):
    _customer_q = []
    _cust_in_time = list(df_customers.time_in.values)
    _reps_avail = []
    _reps_busy = []
    
    for t in range(time_periods): # Step through each time period 
        if t in _cust_in_time: # If one or more custommers enter at that time
            _customer_q += list(df_customers[df_customers.time_in==t].customer_id.values) # Append them to the queue

        for customer_qued in _customer_q: # look through the queue

            for rep in df_reps.columns:
                if df_reps.at[t, rep] ==0:
                    _req_call_time = int(df_customers[df_customers.customer_id==customer_qued]['required_call_time'])
                    df_customers.at[df_customers.customer_id==customer_qued, ['time_assigned', 'time_out',  'assigned_rep']] = [t, t+_req_call_time , rep]

                    df_reps.loc[t: t + _req_call_time, rep] = 1
                    break
        df_q.at[t,'customer_q_list'] = _customer_q
        
    df_customers['wait_time'] = df_customers.time_assigned - df_customers.time_in
    df_customers['iteration'] = iteration

    df_txn_log = pd.concat([df_q, df_reps],axis=1)
    df_txn_log['num_in_q'] = df_txn_log.customer_q_list.apply(lambda x: len(x))
    df_txn_log['iteration'] = iteration
    df_txn_log = df_txn_log.iloc[:df_customers.time_out.max()+1, :]
    return df_customers, df_txn_log

In [15]:
%%time
df_customers, df_txn_log = run_day(generate_customer_table(num_customers=num_customerz, time_periods=time_periodz, seed=42), 
                                   generate_qs(time_periodz), 
                                   generate_reps(num_repz, time_periodz), 
                                   iteration=1, 
                                  time_periods=time_periodz)

"""
Timed: 5 min 30 s. 2min 44 with basic list cut
num_customerz = 10*24
time_periodz = 24*60
num_repz = 50
"""

CPU times: user 7.83 s, sys: 0 ns, total: 7.83 s
Wall time: 7.83 s

In [16]:
df_txn_log.tail()

,customer_q_list,update_event,rep1_busy,rep2_busy,rep3_busy,rep4_busy,rep5_busy,num_in_q,iteration
995,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",0,1,1,1,1,1,200,1
996,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",0,1,1,1,1,1,200,1
997,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",0,1,1,1,1,1,200,1
998,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",0,1,1,1,1,1,200,1
999,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",0,1,1,1,1,1,200,1

In [17]:
df_customers

,customer_id,required_call_time,time_in,time_out,time_assigned,assigned_rep,wait_time,iteration
53,1,5,2,1004,999,rep2_busy,997,1
61,2,4,9,0,0,none,-9,1
150,3,1,17,0,0,none,-17,1
181,4,3,18,0,0,none,-18,1
122,5,5,22,0,0,none,-22,1
132,6,4,27,0,0,none,-27,1
115,7,5,33,0,0,none,-33,1
59,8,2,37,0,0,none,-37,1
161,9,1,37,0,0,none,-37,1
125,10,4,38,0,0,none,-38,1
155,11,1,46,0,0,none,-46,1
148,12,2,49,0,0,none,-49,1
70,13,1,54,0,0,none,-54,1
158,14,1,99,0,0,none,-99,1
63,15,2,99,0,0,none,-99,1
168,16,1,99,0,0,none,-99,1
87,17,1,99,0,0,none,-99,1
80,18,5,104,0,0,none,-104,1
84,19,1,112,0,0,none,-112,1
171,20,1,116,0,0,none,-116,1
71,21,5,120,0,0,none,-120,1
9,22,5,124,0,0,none,-124,1
180,23,1,128,0,0,none,-128,1
67,24,2,131,0,0,none,-131,1
111,25,3,135,0,0,none,-135,1
48,26,2,144,0,0,none,-144,1
6,27,3,144,0,0,none,-144,1
23,28,1,147,0,0,none,-147,1
24,29,1,148,0,0,none,-148,1
41,30,1,151,0,0,none,-151,1
...,...,...,...,...,...,...,...,...
119,171,2,883,0,0,none,-883,1
159,172,3,892,0,0,none,-892,1
109,173,3,896,0,0,none,-896,1
91,174,1,896,0,0,none,-896,1
54,175,3,897,0,0,none,-897,1
3,176,5,907,0,0,none,-907,1
90,177,3,914,0,0,none,-914,1
107,178,4,916,0,0,none,-916,1
73,179,2,920,0,0,none,-920,1
175,180,2,928,0,0,none,-928,1
29,181,4,929,0,0,none,-929,1
18,182,1,932,0,0,none,-932,1
30,183,3,936,0,0,none,-936,1
192,184,4,943,0,0,none,-943,1
40,185,4,946,0,0,none,-946,1
38,186,1,953,0,0,none,-953,1
17,187,5,955,0,0,none,-955,1
118,188,1,955,0,0,none,-955,1
98,189,2,957,0,0,none,-957,1
139,190,5,960,0,0,none,-960,1
195,191,3,962,0,0,none,-962,1
21,192,5,963,0,0,none,-963,1
77,193,4,968,0,0,none,-968,1
174,194,4,981,0,0,none,-981,1
2,195,3,982,0,0,none,-982,1
176,196,3,983,0,0,none,-983,1
37,197,5,988,0,0,none,-988,1
43,198,2,990,0,0,none,-990,1
170,199,1,993,0,0,none,-993,1
100,200,4,996,0,0,none,-996,1

# Run a whole week

In [10]:
for i in range(2,10):
    df_a, df_b = run_day(generate_customer_table(), 
                                   generate_qs(), 
                                   generate_reps(), 
                                   iteration=i)
    df_customers = pd.concat([df_customers, df_a])
    df_txn_log = pd.concat([df_txn_log, df_b])

NameError: name 'time_periods' is not defined

In [32]:
# Wait Times
np.quantile(df_customers.wait_time, [.25, .5, .99])

array([ 8.  , 18.  , 41.01])

In [33]:
# Rep utilization rates
df_txn_log.loc[:, ['rep1_busy', 'rep2_busy', 'rep3_busy']].mean()

rep1_busy    0.977866
rep2_busy    0.969170
rep3_busy    0.938340
dtype: float64